name: Backend testing
on: 
  workflow_call:
    secrets:
      DATABASE_NAME:
        required: true
      DATABASE_URL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs 
        pipreqs --force
        pip install -r requirements.txt
    - name: Test with pytest
      working-directory: ./backend
      env:
        DATABASE_NAME:  ${{ secrets.DATABASE_NAME }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        pip install pytest pytest-cov httpx
        python -c 'import os; print("DATABASE_NAME",os.getenv("DATABASE_NAME"))'
        python -c 'import os; print("DATABASE_URL",os.getenv("DATABASE_URL"))'
        python -c 'import os; print("environments:",os.environ)'
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
